### ISSUE TITLE
NODE_ENV value of 'production' did not match any deployment config file names.

### ISSUE THREAD

**Issue by JimBarrows** [JimBarrows/SavageWorldsVirtualTableTop#78]
WARNING: NODE_ENV value of 'production' did not match any deployment config file names.
user_api    | WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode

**Comment by sscodes** [comment]
@JimBarrows Have you got any solution to the issue? I'm also facing the same problem.
